SCREEN_WIDTH = 500
SCREEN_HEIGHT = 400
FPS = 120
TICK = True

# Colors
BLACK = [0, 0, 0]
WHITE = [255, 255, 255]

# Paddle PARAMS
PADDLE_WIDTH = 20
PADDLE_HEIGHT = PADDLE_WIDTH * 3
PADDLE_INDENT = 0
PADDLE_Y_START = SCREEN_HEIGHT // 2 - PADDLE_HEIGHT 
PADDLE_SPEED = 10

# Ball PARAMS

BALL_WIDTH = PADDLE_WIDTH
BALL_HEIGHT = BALL_WIDTH
BALL_START_X = SCREEN_WIDTH // 2 - BALL_WIDTH // 2
BALL_START_Y = 0
BALL_STARTING_X_SPEED = 2
BALL_STARTING_Y_SPEED = - 2
BALL_SPEED_INCREASE = 0.0

# Neural Network Params
NUMBER_OF_RAYS = 20
RAY_LENGTH = 400
SENSOR_DEGREE_OPENING = 160
NUMBER_OF_NEURONS = 25 # 25
NUMBER_OF_LEVELS = 1 # 1
MUTATE_AMOUNT = 0.1
GENETIC_TRAIN = False
LOAD_NETWORK = True
NETWORK_PATH = 'saves/save_complete.json'
NETWORK_FOLDER = 'saves/'

